scheduled-messages:
  interval-minutes: 3
  messages:
      - "Â§e[ğŸ””] é»˜è®¤èŠå¤©ä¸ºé˜Ÿä¼èŠå¤©ï¼Œä½ å¯ä»¥ä½¿ç”¨ /s <å†…å®¹> è¿›è¡Œå–Šè¯"
      - "Â§e[ğŸ””] å¦‚æœ50æ ¼å†…æœ‰æ•Œäººï¼Œä½ ä¸èƒ½æ‰“å¼€å…±äº«èƒŒåŒ…æˆ–ä¼ é€èœå•"
      - "Â§e[ğŸ””] æ¸¸æˆå¼€å§‹30åˆ†é’Ÿåï¼Œå°†ä¸å…è®¸æ–°ç©å®¶åŠ å…¥"
glass-frozen-time: 30
waiting-time: 60
spawn-distance: 300
